<a href="https://colab.research.google.com/github/Davron030901/Calculator/blob/main/Chiziqli_Algebra_Vazifa_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vazifa 1: Vektor va Vektor Algebra

## Vazifa 1.1: Vektor ustida amallar

Agar $\textbf{u}= \begin{bmatrix} 5 \\ 2 \\ 9 \end{bmatrix}$ va $\textbf{v}= \begin{bmatrix} 1 \\ -8 \\ 6 \end{bmatrix}$, $c=0.5$ bo'lsa, quyidagilarni bajaring:

1. $\textbf{u} + \textbf{v}$
2. $\textbf{u} - \textbf{v}$
3. $c\textbf{u}$
4. $\textbf{v}$ uzunligi
5. $\textbf{u}$ larining birlik vektori ko'rinishi



In [1]:
import numpy as np
u=np.array([5,2,9])
v=np.array([1,-8,6])
c=0.5
print(u+v)
print(u-v)
print(c*u)
print(np.linalg.norm(v))
print(u/np.linalg.norm(u))
print(v/np.linalg.norm(v))

[ 6 -6 15]
[ 4 10  3]
[2.5 1.  4.5]
10.04987562112089
[0.47673129 0.19069252 0.85811633]
[ 0.09950372 -0.79602975  0.59702231]


## Vazifa 1.2: Vektorlar normasi va skalyar ko'paytma

Agar $\textbf{u}= \begin{bmatrix} 1 \\ -1 \\ 2 \end{bmatrix}$ va $\textbf{v}= \begin{bmatrix} 3 \\ -1 \\ 4 \end{bmatrix}$, quyidagilarni toping:

1. $\textbf{u}$ vektorining $L_1$ normasi
2. $\textbf{v}$ vektorining $L_2$ normasi
3. $\textbf{u} \cdot \textbf{v}$
4. $d(\textbf{u}, \textbf{v})$ (Evklid masofa)
5. $\textbf{u}$ va $\textbf{v}$ orasidagi burchak



In [2]:
u=np.array([1,-1,2])
v=np.array([3,-1,4])
l1_norm=np.linalg.norm(u,1)
print(l1_norm)
l2_norm=np.linalg.norm(v,2)
print(l2_norm)
dot_p=np.dot(u,v)
print(dot_p)
evklit=np.linalg.norm(u-v)
print(evklit)
cos_theta=dot_p/(np.linalg.norm(u)*np.linalg.norm(v))
print(cos_theta)
theta=np.arccos(cos_theta)
print(theta*180/np.pi)

4.0
5.0990195135927845
12
2.8284271247461903
0.960768922830523
16.102113751985986


## Vazifa 1.3: Chiziqli bog'liqlik

Quyidagilarni aniqlang:

1. $\textbf{u}= \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \textbf{v}= \begin{bmatrix} 3 \\ 4 \end{bmatrix}, \textbf{w}= \begin{bmatrix} 5 \\ 6 \end{bmatrix}$ chiziqli bog'liqmi?

2. $\textbf{u}= \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \textbf{v}= \begin{bmatrix} 3 \\ 4 \end{bmatrix}, \textbf{w}= \begin{bmatrix} 8 \\ 14 \end{bmatrix}$ chiziqli bog'liqmi?




In [3]:
u1 = np.array([1, 2])
v1 = np.array([3, 4])
w1 = np.array([5, 6])

u2 = np.array([1, 2])
v2 = np.array([3, 4])
w2 = np.array([8, 14])


def check_linear_combination(u, v, w):
    A = np.column_stack((u, v))
    coefficients, _, _, _ = np.linalg.lstsq(A, w, rcond=None)
    w_reconstructed = coefficients[0] * u + coefficients[1] * v
    difference = np.linalg.norm(w - w_reconstructed)
    return coefficients, difference

coeffs1, diff1 = check_linear_combination(u1, v1, w1)
print("1-holat:")
print("Koefitsientlar (a, b):", coeffs1)
print("Farq (norm):", diff1)
if diff1 < 1e-10:
    print("Chiziqli bog'liq!")
else:
    print("Chiziqli mustaqil!")

coeffs2, diff2 = check_linear_combination(u2, v2, w2)
print("\n2-holat:")
print("Koefitsientlar (a, b):", coeffs2)
print("Farq (norm):", diff2)
if diff2 < 1e-10:
    print("Chiziqli bog'liq!")
else:
    print("Chiziqli mustaqil!")

1-holat:
Koefitsientlar (a, b): [-1.  2.]
Farq (norm): 1.7763568394002505e-15
Chiziqli bog'liq!

2-holat:
Koefitsientlar (a, b): [5. 1.]
Farq (norm): 8.881784197001252e-15
Chiziqli bog'liq!


# 📌 Mini-Loyiha: Oddiy Film Tavsiya Qiluvchi Tizim

![Netflix](https://img.shields.io/badge/Netflix-E50914?style=for-the-badge&logo=netflix&logoColor=white)
Tasavvur qiling siz Netflix  companiyasida ishlayapsiz. Ma'lumotlar bazasi:

| Film nomi         | Jangari ⚔️ | Romantik 💕 | Fantastika 🚀 | Drama 🎭 | Komediya 😂 |
|------------------|----------|-----------|--------------|----------|------------|
| **Sheryurak**    | 5        | 1         | 2            | 1        | 0          |
| **Titanik**      | 1        | 4         | 2            | 2        | 1          |
| **Avatar**       | 3        | 2         | 5            | 2        | 1          |
| **Buyuk Getsbi** | 1        | 2         | 3            | 4        | 0          |
| **Pushti Pantera** | 1      | 1         | 4            | 1        | 5          |

**Foydalanuvchi qiziqishlari**:
```python
[Jangari = 5, Romantik = 3, Fantastika = 1, Drama = 2, Komediya = 2]
```

🎯 **Maqsad**: Foydalanuvchining yoqtirgan kino janrlariga asoslanib, unga mos filmlarni tavsiya qilish.

-------
📌 **Bosqichlar**:
1. Foydalanuvchi qiziqishini vektor shaklida ifodalash
    - Foydalanuvchi har bir janr bo‘yicha nechta filmga "like" berganini ko‘rsatadi
    
2. Filmlar janrlariga qarab vektor shaklida ifodalash:
    - Har bir filmni quyidagi formatda ifodalaymiz:
```python
                    [5, 1, 2, 1, 0] # Sheryurak
                    [1, 4, 2, 2, 1] # Titanik
                    [3, 2, 5, 2, 1] # Avatar
                    [1, 2, 3, 4, 0] # Buyuk Getsbi
                    [1, 1, 4, 1, 5] # Pushti Pantera
```
    - Bu vektorda har bir qiymat o‘sha film qaysi janrga qanchalik tegishli ekanini bildiradi.

3. Foydalanuvchi qiziqishi bilan filmlar orasidagi o‘xshashlikni hisoblash
    - Har bir film foydalanuvchi qiziqishlariga qanchalik yaqin ekanini aniqlash.
    - Buning uchun **kosinus o‘xshashlik** metodi foydalanamiz.


4. Foydalanuvchiga eng mos keladigan TOP-3 filmlarni tavsiya qilish
    - O‘xshashlik bo‘yicha eng yuqori natijalarga ega filmlarni tanlash.

In [4]:
import numpy as np
from scipy.linalg import null_space

foydalanuvchi= np.array([5, 3, 1, 2, 2])
filmlar={
"Sheryurak":np.array([5, 1, 2, 1, 0]),
"Titanik":np.array([1, 4, 2, 2, 1]),
"Avatar":np.array([3, 2, 5, 2, 1]),
"Buyuk Getsbi":np.array([1, 2, 3, 4, 0]),
"Pushti Pantera":np.array([1, 1, 4, 1, 5])
}

In [6]:
# Qadam 3:
tavsiya=[]
for film_nomi,reyting in filmlar.items():
  cos_sim=np.dot(reyting,foydalanuvchi)/(np.linalg.norm(reyting)*np.linalg.norm(foydalanuvchi))
  tavsiya.append((film_nomi,cos_sim))
tavsiya

[('Sheryurak', 0.8764656570636428),
 ('Titanik', 0.747685755693224),
 ('Avatar', 0.744186046511628),
 ('Buyuk Getsbi', 0.612530651028675),
 ('Pushti Pantera', 0.5517605878460435)]

In [8]:
# Qadam 4:
tavsiya=sorted(tavsiya,key=lambda x:x[1],reverse=True)
for i in range(3):
  film_nomi,cos_sim=tavsiya[i]
  print(f"{film_nomi} - {cos_sim}")

Sheryurak - 0.8764656570636428
Titanik - 0.747685755693224
Avatar - 0.744186046511628
